version: '3'
services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "15432:5432"
    restart: always
    environment:
      POSTGRES_DB: gogetit
      POSTGRES_USER: gogetit
      POSTGRES_PASSWORD: gogetit